# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lks3eR0qW3AQUbq7LB4i1aNMzFrc11HD
"""





# Load model




age = number_input("Age", min_value=18, max_value=100)
income = number_input("Annual Income")
debt = number_input("Existing Debt")

if button("Predict"):

    # Create sample input
    sample = pd.DataFrame({
        "Age": [age],
        "Annual_Income_INR": [income],
        "Existing_Debt": [debt]
    })

    prediction = model.predict(sample)

    if prediction[0] == 1:
        success("Good Credit Risk")
    else:
        error("Bad Credit Risk")

